name: Auth Bouncer CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  auth-bouncer-php-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: docker run -it --rm --name bouncer-dependency-installation -v "$PWD":/usr/src/bouncer -w /usr/src/bouncer adjvo/auth-backend-api-base composer install -o
    - name: Run tests
      run: docker run -it --rm --name bouncer-tests-runner -v "$PWD":/usr/src/bouncer -w /usr/src/bouncer adjvo/auth-backend-api-base vendor/bin/phpunit tests --testdox

